version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: dev_dive_db
    networks:
      - common_network
    env_file:
      - .env
    volumes:
      - ~/dev_dive/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - common_network
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: /code/start.sh

networks:
  common_network:
    name: common_network
    driver: bridge