version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: "postgres"
    networks:
      - common_network
    env_file:
      - .env
    volumes:
      - ~/app/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"

  redis:
    image: redis:7.2
    container_name: "redis"
    networks:
      - common_network
    ports:
      - "6379:6379"
    expose:
      - "6379"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ~/app/redis:/var/lib/redis/data


  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${SECRET_KEY}
    volumes:
      - ~/app/minio:/data
    command: server /data --console-address ":9001"

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    networks:
#      - common_network
#    volumes:
#      - ./src:/src
#    ports:
#      - "8000:8000"
#    expose:
#      - "8000"
#    command: /code/start.sh

networks:
  common_network:
    name: common_network
    driver: bridge